import type { Ticket } from "@/types/ticket";

export const mockTickets: Ticket[] = [
  {
    id: "1",
    ticketCode: "TK-001",
    title: "صفحه ورود در دستگاه‌های موبایل به درستی بارگذاری نمی‌شود",
    description:
      "کاربران گزارش می‌دهند که صفحه ورود در دستگاه‌های موبایل به طور کامل بارگذاری نمی‌شود، به ویژه در مرورگرهای Safari iOS و Chrome موبایل. عناصر فرم ناقص نمایش داده می‌شوند و دکمه ثبت قابل مشاهده نیست.",
    status: "open",
    priority: "high",
    service: "technical",
    requester: { id: "1", name: "محمد احمدی", avatar: "محمد احمدی" },
    assignee: { id: "2", name: "سارا رضایی", avatar: "سارا رضایی" },
    createdAt: "1402-10-25T14:00:15+03:30",
    lastUpdated: "1402-10-25T14:02:40+03:30",
    dueDate: "1402-10-25T15:30:00+03:30",
    estimatedHours: 2,
    timeSpent: 0,
    isTimerActive: false,
    isPinned: true,
    tags: ["موبایل", "ورود", "اولویت بالا"],
    comments: [
      {
        id: "1",
        content: "این تیکت ایجاد شد و نیاز به بررسی فوری دارد",
        author: { id: "1", name: "محمد احمدی", avatar: "محمد احمدی" },
        createdAt: "1402-10-25T14:00:25+03:30",
        type: "comment",
      },
      {
        id: "1-2",
        content: "بازتولید مشکل روی iPhone 12 در Safari تایید شد.",
        author: { id: "2", name: "سارا رضایی", avatar: "سارا رضایی" },
        createdAt: "1402-10-25T14:01:35+03:30",
        type: "comment",
      },
      {
        id: "1-3",
        content: "در حال بررسی CSS مربوط به viewport و safe-area هستم.",
        author: { id: "2", name: "سارا رضایی", avatar: "సارا رضایی" as any },
        createdAt: "1402-10-25T14:02:40+03:30",
        type: "status-change",
      },
    ],
    attachments: [],
  },
  {
    id: "2",
    ticketCode: "TK-002",
    title: "مشکلات عملکرد داشبورد با مجموعه داده‌های بزرگ",
    description:
      "داشبورد اصلی هنگام بارگذاری مجموعه داده‌هایی با بیش از ۱۰,۰۰۰ رکورد پاسخگو نمی‌شود. زمان بارگذاری صفحه از ۳۰ ثانیه بیشتر می‌شود و گاهی منجر به خرابی مرورگر می‌شود.",
    status: "in-progress",
    priority: "medium",
    service: "technical",
    requester: { id: "3", name: "علی کریمی", avatar: "علی کریمی" },
    assignee: { id: "4", name: "فاطمه نوری", avatar: "فاطمه نوری" },
    createdAt: "1402-10-25T12:45:05+03:30",
    lastUpdated: "1402-10-25T12:55:30+03:30",
    dueDate: "1402-10-25T14:30:00+03:30",
    estimatedHours: 3,
    timeSpent: 1,
    isTimerActive: false,
    timerStartTime: "1402-10-25T12:50:00+03:30",
    isPinned: false,
    tags: ["عملکرد", "داشبورد", "بهینه‌سازی"],
    comments: [
      {
        id: "2",
        content: "شروع به بررسی مشکل کردم",
        author: { id: "4", name: "فاطمه نوری", avatar: "فاطمه نوری" },
        createdAt: "1402-10-25T12:46:00+03:30",
        type: "status-change",
      },
      {
        id: "3",
        content: "مشکل در پردازش داده‌های بزرگ شناسایی شد",
        author: { id: "4", name: "فاطمه نوری", avatar: "فاطمه نوری" },
        createdAt: "1402-10-25T12:55:30+03:30",
        type: "comment",
      },
      {
        id: "2-3",
        content: "پیشنهاد: مجازی‌سازی جدول و pagination سمت سرور برای کاهش memory footprint.",
        author: { id: "4", name: "فاطمه نوری", avatar: "فاطمه نوری" },
        createdAt: "1402-10-25T12:55:30+03:30",
        type: "comment",
      },
    ],
    attachments: [],
  },
  {
    id: "3",
    ticketCode: "TK-003",
    title: "اعلان‌های ایمیل برای ثبت‌نام کاربران جدید ارسال نمی‌شود",
    description:
      "کاربران جدید پس از تکمیل فرآیند ثبت‌نام، ایمیل‌های خوش‌آمدگویی دریافت نمی‌کنند. سرویس ایمیل برای سایر انواع اعلان‌ها به نظر کار می‌کند.",
    status: "open",
    priority: "high",
    service: "technical",
    requester: { id: "5", name: "حسن موسوی", avatar: "حسن موسوی" },
    assignee: { id: "6", name: "مریم قاسمی", avatar: "مریم قاسمی" },
    createdAt: "1402-10-25T11:30:20+03:30",
    lastUpdated: "1402-10-25T11:33:15+03:30",
    dueDate: "1402-10-25T13:00:00+03:30",
    estimatedHours: 1,
    timeSpent: 0,
    isTimerActive: false,
    isPinned: false,
    tags: ["ایمیل", "ثبت‌نام", "اعلان"],
    comments: [
      {
        id: "4",
        content: "مشکل ایمیل گزارش شده است",
        author: { id: "5", name: "حسن موسوی", avatar: "حسن موسوی" },
        createdAt: "1402-10-25T11:30:40+03:30",
        type: "comment",
      },
      {
        id: "3-2",
        content: "وب‌هوک ثبت‌نام به صف ارسال ایمیل نرسیده؛ بررسی سرویس queue انجام می‌شود.",
        author: { id: "6", name: "مریم قاسمی", avatar: "مریم قاسمی" },
        createdAt: "1402-10-25T11:33:15+03:30",
        type: "comment",
      },
    ],
    attachments: [],
  },
  {
    id: "4",
    ticketCode: "TK-004",
    title: "درخواست ویژگی: افزودن قابلیت تصویر پروفایل کاربر",
    description:
      "کاربران درخواست کرده‌اند که امکان آپلود و به‌روزرسانی تصاویر پروفایل اضافه شود. این باید شامل فشرده‌سازی تصویر و اعتبارسنجی فرمت فایل مناسب باشد.",
    status: "closed",
    priority: "low",
    service: "feature-request",
    requester: { id: "7", name: "زهرا احمدی", avatar: "زهرا احمدی" },
    assignee: { id: "8", name: "امیر حسینی", avatar: "امیر حسینی" },
    createdAt: "1402-10-25T10:30:10+03:30",
    lastUpdated: "1402-10-25T11:15:55+03:30",
    dueDate: "1402-10-25T11:30:00+03:30",
    estimatedHours: 1,
    timeSpent: 1,
    isTimerActive: false,
    isPinned: false,
    tags: ["ویژگی جدید", "پروفایل", "تصویر"],
    comments: [
      {
        id: "5",
        content: "ویژگی با موفقیت پیاده‌سازی شد",
        author: { id: "8", name: "امیر حسینی", avatar: "امیر حسینی" },
        createdAt: "1402-10-25T11:15:55+03:30",
        type: "status-change",
      },
      {
        id: "4-2",
        content: "اعتبارسنجی MIME و حداکثر اندازه ۲ مگابایت اضافه شد.",
        author: { id: "8", name: "امیر حسینی", avatar: "امیر حسینی" },
        createdAt: "1402-10-25T11:12:10+03:30",
        type: "comment",
      },
    ],
    attachments: [],
  },
  {
    id: "5",
    ticketCode: "TK-005",
    title: "خطای critical در سیستم پرداخت",
    description:
      "سیستم پرداخت دچار خطای شدید شده و تراکنش‌ها با شکست مواجه می‌شوند. این مسئله فوری نیاز به حل دارد.",
    status: "in-progress",
    priority: "critical",
    service: "billing",
    requester: { id: "9", name: "رضا صادقی", avatar: "رضا صادقی" },
    assignee: { id: "10", name: "سمیرا کاظمی", avatar: "سمیرا کاظمی" },
    createdAt: "1402-10-25T11:30:10+03:30",
    lastUpdated: "1402-10-25T12:42:30+03:30",
    dueDate: "1402-10-25T15:30:00+03:30",
    estimatedHours: 6,
    timeSpent: 2,
    isTimerActive: false,
    timerStartTime: "1402-10-25T12:00:00+03:30",
    isPinned: true,
    tags: ["critical", "پرداخت", "فوری"],
    comments: [
      {
        id: "6",
        content: "مشکل پرداخت critical گزارش شد",
        author: { id: "9", name: "رضا صادقی", avatar: "رضا صادقی" },
        createdAt: "1402-10-25T11:30:20+03:30",
        type: "comment",
      },
      {
        id: "7",
        content: "شروع به بررسی فوری کردم",
        author: { id: "10", name: "سمیرا کاظمی", avatar: "سمیرا کاظمی" },
        createdAt: "1402-10-25T12:00:15+03:30",
        type: "status-change",
      },
      {
        id: "5-3",
        content: "درگاه دوم موقتاً فعال شد؛ خطا مربوط به timeouts سمت PSP اول است.",
        author: { id: "10", name: "سمیرا کاظمی", avatar: "سمیرا کاظمی" },
        createdAt: "1402-10-25T12:42:30+03:30",
        type: "comment",
      },
    ],
    attachments: [],
  },
  {
    id: "6",
    ticketCode: "TK-006",
    title: "سوال عمومی درباره نحوه استفاده از API",
    description: "کاربر سوالی درباره نحوه صحیح استفاده از API و مستندات آن دارد.",
    status: "open",
    priority: "low",
    service: "general",
    requester: { id: "11", name: "مهدی رحیمی", avatar: "مهدی رحیمی" },
    assignee: { id: "12", name: "نگار فرهادی", avatar: "نگار فرهادی" },
    createdAt: "1402-10-24T18:00:05+03:30",
    lastUpdated: "1402-10-24T18:05:40+03:30",
    dueDate: "1402-10-24T19:30:00+03:30",
    estimatedHours: 2,
    timeSpent: 0,
    isTimerActive: false,
    isPinned: false,
    tags: ["سوال", "API", "مستندات"],
    comments: [
      {
        id: "6-1",
        content: "لینک مستندات v2 ارسال شد و پیشنهاد استفاده از کلید sandbox داده شد.",
        author: { id: "12", name: "نگار فرهادی", avatar: "نگار فرهادی" },
        createdAt: "1402-10-24T18:05:40+03:30",
        type: "comment",
      },
    ],
    attachments: [],
  },
  {
    id: "7",
    ticketCode: "TK-007",
    title: "گزارش باگ: خطا در صفحه گزارش‌ها",
    description: "صفحه گزارش‌ها خطای 500 نمایش می‌دهد و نمودارها بارگذاری نمی‌شوند.",
    status: "open",
    priority: "medium",
    service: "bug-report",
    requester: { id: "13", name: "احمد نظری", avatar: "احمد نظری" },
    assignee: { id: "14", name: "لیلا صفری", avatar: "لیلا صفری" },
    createdAt: "1402-10-25T16:45:10+03:30",
    lastUpdated: "1402-10-25T16:48:45+03:30",
    dueDate: "1402-10-25T19:00:00+03:30",
    estimatedHours: 2,
    timeSpent: 0,
    isTimerActive: false,
    isPinned: false,
    tags: ["باگ", "گزارش", "نمودار"],
    comments: [
      {
        id: "8",
        content: "باگ گزارش شده و در حال بررسی است",
        author: { id: "13", name: "احمد نظری", avatar: "احمد نظری" },
        createdAt: "1402-10-25T16:45:25+03:30",
        type: "comment",
      },
      {
        id: "7-2",
        content: "احتمالاً کوئری aggregate سنگین باعث timeout سرویس گزارش شده.",
        author: { id: "14", name: "لیلا صفری", avatar: "لیلا صفری" },
        createdAt: "1402-10-25T16:48:45+03:30",
        type: "comment",
      },
    ],
    attachments: [],
  },
  {
    id: "8",
    ticketCode: "TK-008",
    title: "مشکل اتصال پایگاه داده",
    description: "اتصال به پایگاه داده دچار مشکل شده و کوئری‌ها با تاخیر اجرا می‌شوند.",
    status: "in-progress",
    priority: "high",
    service: "technical",
    requester: { id: "15", name: "مسعود جعفری", avatar: "مسعود جعفری" },
    assignee: { id: "2", name: "سارا رضایی", avatar: "سارا رضایی" },
    createdAt: "1402-10-25T11:15:05+03:30",
    lastUpdated: "1402-10-25T13:40:30+03:30",
    dueDate: "1402-10-25T16:00:00+03:30",
    estimatedHours: 3,
    timeSpent: 1,
    isTimerActive: false,
    isPinned: false,
    tags: ["پایگاه داده", "عملکرد", "اتصال"],
    comments: [
      {
        id: "9",
        content: "مشکل اتصال پایگاه داده شناسایی شد",
        author: { id: "15", name: "مسعود جعفری", avatar: "مسعود جعفری" },
        createdAt: "1402-10-25T11:15:25+03:30",
        type: "comment",
      },
      {
        id: "8-2",
        content: "pool-size افزایش داده شد و retry با backoff افزوده شد.",
        author: { id: "2", name: "سارا رضایی", avatar: "سارا رضایی" },
        createdAt: "1402-10-25T13:40:30+03:30",
        type: "comment",
      },
    ],
    attachments: [],
  },
];
